// <auto-generated />
using System;
using DogQuiz.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogQuiz.MigrationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241123195038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BreedBreedMix", b =>
                {
                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("BreedMixId")
                        .HasColumnType("int");

                    b.HasKey("BreedId", "BreedMixId");

                    b.HasIndex("BreedMixId");

                    b.ToTable("BreedBreedMix");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1250)
                        .HasColumnType("nvarchar(1250)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("OriginId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ImageId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OriginId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedMix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1250)
                        .HasColumnType("nvarchar(1250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("PrimaryImageId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("PrimaryImageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("BreedMixes");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedVarietyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("BreedVarietyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("BreedNames");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedOrigin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HistoricalContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BreedOrigin");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("BreedRoles");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("BreedVarieties");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.NotableDog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedMixId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedVarietyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1250)
                        .HasColumnType("nvarchar(1250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KnownFor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("PrimaryImageId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("BreedMixId");

                    b.HasIndex("BreedVarietyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("PrimaryImageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("NotableDogs");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.NotableOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedMixId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedVarietyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1250)
                        .HasColumnType("nvarchar(1250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KnownFor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("PrimaryImageId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("BreedMixId");

                    b.HasIndex("BreedVarietyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("PrimaryImageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("NotableOwners");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Bases.Answer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ImageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Answers");

                    b.HasDiscriminator<string>("AnswerType").HasValue("Answer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Bases.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedMixId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedVarietyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("NotableDogId")
                        .HasColumnType("int");

                    b.Property<int?>("NotableOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Text")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("BreedMixId");

                    b.HasIndex("BreedVarietyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("NotableDogId");

                    b.HasIndex("NotableOwnerId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("QuestionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerMultipleSelectId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerMultipleSelectId");

                    b.ToTable("Choice");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.Fact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("DogQuiz.Domain.Shared.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreedOriginId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumericCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThreeLetterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoLetterCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BreedOriginId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DogQuiz.Domain.Shared.Entities.ImageDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedMixId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Folder")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("License")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NotableDogId")
                        .HasColumnType("int");

                    b.Property<int?>("NotableOwnerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("BreedMixId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NotableDogId");

                    b.HasIndex("NotableOwnerId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ImageDetails");
                });

            modelBuilder.Entity("DogQuiz.Domain.Shared.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreedId")
                        .HasColumnType("int");

                    b.Property<int?>("BreedVarietyId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("BreedVarietyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DogQuiz.Domain.Users.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DogQuiz.Domain.Users.Entities.PermissionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("PermissionRoles");
                });

            modelBuilder.Entity("DogQuiz.Domain.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("IdentityProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PermissionRolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionRoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "PermissionRoleId");

                    b.HasIndex("PermissionRoleId");

                    b.ToTable("PermissionRolePermission");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.AnswerMultipleSelect", b =>
                {
                    b.HasBaseType("DogQuiz.Domain.Questions.Bases.Answer");

                    b.HasDiscriminator().HasValue("MultipleSelect");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.AnswerSingleSelect", b =>
                {
                    b.HasBaseType("DogQuiz.Domain.Questions.Bases.Answer");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("int");

                    b.HasIndex("ChoiceId");

                    b.HasDiscriminator().HasValue("SingleSelect");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.AnswerTrueFalse", b =>
                {
                    b.HasBaseType("DogQuiz.Domain.Questions.Bases.Answer");

                    b.Property<bool>("Answer")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("TrueFalse");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.QuestionGeneral", b =>
                {
                    b.HasBaseType("DogQuiz.Domain.Questions.Bases.Question");

                    b.HasDiscriminator().HasValue("General");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.QuestionImage", b =>
                {
                    b.HasBaseType("DogQuiz.Domain.Questions.Bases.Question");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageQuestionType")
                        .HasColumnType("int");

                    b.HasIndex("ImageId");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.QuestionText", b =>
                {
                    b.HasBaseType("DogQuiz.Domain.Questions.Bases.Question");

                    b.Property<int?>("TextQuestionType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("BreedBreedMix", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", null)
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedMix", null)
                        .WithMany()
                        .HasForeignKey("BreedMixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.Breed", b =>
                {
                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Shared.Entities.ImageDetail", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedOrigin", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Image");

                    b.Navigation("Origin");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedMix", b =>
                {
                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Shared.Entities.ImageDetail", "PrimaryImage")
                        .WithMany()
                        .HasForeignKey("PrimaryImageId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("PrimaryImage");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedName", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", "Breed")
                        .WithMany("AdditionalNames")
                        .HasForeignKey("BreedId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedVariety", "BreedVariety")
                        .WithMany()
                        .HasForeignKey("BreedVarietyId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Breed");

                    b.Navigation("BreedVariety");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedRole", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", "Breed")
                        .WithMany("Roles")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Breed");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedVariety", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", "Breed")
                        .WithMany("Varieties")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Breed");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.NotableDog", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", "Breed")
                        .WithMany("NotableDogs")
                        .HasForeignKey("BreedId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedMix", "BreedMix")
                        .WithMany()
                        .HasForeignKey("BreedMixId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedVariety", "BreedVariety")
                        .WithMany()
                        .HasForeignKey("BreedVarietyId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Shared.Entities.ImageDetail", "PrimaryImage")
                        .WithMany()
                        .HasForeignKey("PrimaryImageId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Breed");

                    b.Navigation("BreedMix");

                    b.Navigation("BreedVariety");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("PrimaryImage");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.NotableOwner", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", "Breed")
                        .WithMany("NotableOwners")
                        .HasForeignKey("BreedId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedMix", "BreedMix")
                        .WithMany()
                        .HasForeignKey("BreedMixId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedVariety", "BreedVariety")
                        .WithMany()
                        .HasForeignKey("BreedVarietyId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Shared.Entities.ImageDetail", "PrimaryImage")
                        .WithMany()
                        .HasForeignKey("PrimaryImageId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Breed");

                    b.Navigation("BreedMix");

                    b.Navigation("BreedVariety");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("PrimaryImage");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Bases.Answer", b =>
                {
                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Questions.Bases.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("DogQuiz.Domain.Questions.Bases.Answer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogQuiz.Domain.Shared.Entities.ImageDetail", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Image");

                    b.Navigation("Question");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Bases.Question", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", "Breed")
                        .WithMany("Questions")
                        .HasForeignKey("BreedId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedMix", "BreedMix")
                        .WithMany("Questions")
                        .HasForeignKey("BreedMixId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedVariety", "BreedVariety")
                        .WithMany("Questions")
                        .HasForeignKey("BreedVarietyId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.NotableDog", "NotableDog")
                        .WithMany()
                        .HasForeignKey("NotableDogId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.NotableOwner", "NotableOwner")
                        .WithMany("Questions")
                        .HasForeignKey("NotableOwnerId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Breed");

                    b.Navigation("BreedMix");

                    b.Navigation("BreedVariety");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("NotableDog");

                    b.Navigation("NotableOwner");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.Choice", b =>
                {
                    b.HasOne("DogQuiz.Domain.Questions.Entities.AnswerMultipleSelect", null)
                        .WithMany("Choices")
                        .HasForeignKey("AnswerMultipleSelectId");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.Fact", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", "Breed")
                        .WithMany("Facts")
                        .HasForeignKey("BreedId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Breed");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Shared.Entities.Country", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedOrigin", null)
                        .WithMany("Countries")
                        .HasForeignKey("BreedOriginId");
                });

            modelBuilder.Entity("DogQuiz.Domain.Shared.Entities.ImageDetail", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", null)
                        .WithMany("AdditionalImages")
                        .HasForeignKey("BreedId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedMix", null)
                        .WithMany("Images")
                        .HasForeignKey("BreedMixId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.NotableDog", null)
                        .WithMany("AdditionalImages")
                        .HasForeignKey("NotableDogId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.NotableOwner", null)
                        .WithMany("AdditionalImages")
                        .HasForeignKey("NotableOwnerId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Shared.Entities.Tag", b =>
                {
                    b.HasOne("DogQuiz.Domain.Breeds.Entities.Breed", null)
                        .WithMany("BreedTags")
                        .HasForeignKey("BreedId");

                    b.HasOne("DogQuiz.Domain.Breeds.Entities.BreedVariety", null)
                        .WithMany("Tags")
                        .HasForeignKey("BreedVarietyId");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DogQuiz.Domain.Users.Entities.Permission", b =>
                {
                    b.HasOne("DogQuiz.Domain.Users.Entities.User", "User")
                        .WithMany("SpecialPermission")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DogQuiz.Domain.Users.Entities.User", b =>
                {
                    b.HasOne("DogQuiz.Domain.Users.Entities.PermissionRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PermissionRolePermission", b =>
                {
                    b.HasOne("DogQuiz.Domain.Users.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogQuiz.Domain.Users.Entities.PermissionRole", null)
                        .WithMany()
                        .HasForeignKey("PermissionRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.AnswerSingleSelect", b =>
                {
                    b.HasOne("DogQuiz.Domain.Questions.Entities.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.QuestionImage", b =>
                {
                    b.HasOne("DogQuiz.Domain.Shared.Entities.ImageDetail", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.Breed", b =>
                {
                    b.Navigation("AdditionalImages");

                    b.Navigation("AdditionalNames");

                    b.Navigation("BreedTags");

                    b.Navigation("Facts");

                    b.Navigation("NotableDogs");

                    b.Navigation("NotableOwners");

                    b.Navigation("Questions");

                    b.Navigation("Roles");

                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedMix", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedOrigin", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.BreedVariety", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.NotableDog", b =>
                {
                    b.Navigation("AdditionalImages");
                });

            modelBuilder.Entity("DogQuiz.Domain.Breeds.Entities.NotableOwner", b =>
                {
                    b.Navigation("AdditionalImages");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Bases.Question", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();
                });

            modelBuilder.Entity("DogQuiz.Domain.Users.Entities.PermissionRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DogQuiz.Domain.Users.Entities.User", b =>
                {
                    b.Navigation("SpecialPermission");
                });

            modelBuilder.Entity("DogQuiz.Domain.Questions.Entities.AnswerMultipleSelect", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
